"""Add APIUsage model

Revision ID: d31f229da315
Revises: d815f1e94c0d
Create Date: 2025-02-16 22:35:09.286591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31f229da315'
down_revision: Union[str, None] = 'd815f1e94c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
